name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw install -DskipITs=false -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.username=${{ secrets.QUARKUS_CONTAINER_IMAGE_USERNAME }} -Dquarkus.container-image.password=${{ secrets.QUARKUS_CONTAINER_IMAGE_PASSWORD }}
