name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build & Push Image
        run: |
          chmod +x mvnw
          ./mvnw install \
            -DskipITs=false \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.username=${{ secrets.QUARKUS_CONTAINER_IMAGE_USERNAME }} \
            -Dquarkus.container-image.password=${{ secrets.QUARKUS_CONTAINER_IMAGE_PASSWORD }} \

      - uses: actions/upload-artifact@v4
        with:
          name: kubernetes
          path: target/kubernetes

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: kubernetes
          path: target/kubernetes

      - uses: actions-hub/kubectl@v1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: kubectl apply -f target/kubernetes.yml